services:
  broker:
    image: apache/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    networks:
      - ninoverse-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nino
      - POSTGRES_PASSWORD=nino
      - POSTGRES_DB=ninoverse
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ninoverse-network

  # ninoverse:
  #   image: ninoverse:0.0.1
  #   ports:
  #     - "3000:7878"
  #   environment:
  #     - SELF_PORT=7878
  #     - PG_HOST=postgres
  #     - PG_PORT=5432
  #     - PG_USER=nino
  #     - PG_PASSWORD=nino
  #     - PG_DB=ninoverse
  #     - KAFKA_BROKER=broker:9092
  #     - KAFKA_TOPIC=ninoverse:1:1
  #     - DATABASE_URL=postgres://nino:nino@localhost:5432/ninoverse
  #   networks:
  #     - ninoverse-network

networks:
  ninoverse-network:
    driver: bridge
